import type { ModuleDef } from "./types";

export const MODULES: ModuleDef[] = [
  {
    id: "pizzan",
    number: 1,
    title: "Dela pizzan",
    subtitle: "Starta din pizzeria — vem ska äga den med dig?",
    emoji: "🍕",
    lessonSlug: "01-vad-ar-en-aktie",
    estMinutes: 7,
    status: "available",
  },
  {
    id: "mr-market",
    number: 2,
    title: "Mr Markets dörrknack",
    subtitle: "Han knackar varje dag. Manisk eller deprimerad?",
    emoji: "🚪",
    lessonSlug: "02-borsen-och-mr-market",
    estMinutes: 5,
    status: "coming-soon",
  },
  {
    id: "lasagne",
    number: 3,
    title: "Bygg lasagnen",
    subtitle: "Dra bolag in i din fond. Diversifiera eller satsa allt?",
    emoji: "🥘",
    lessonSlug: "03-fonder-lasagne",
    estMinutes: 8,
    status: "coming-soon",
  },
  {
    id: "snoboll",
    number: 4,
    title: "Snöbollsbacken",
    subtitle: "Släpp snöbollen. Stå emot frestelserna i 30 år.",
    emoji: "❄️",
    lessonSlug: "04-ranta-pa-ranta",
    estMinutes: 5,
    status: "coming-soon",
  },
  {
    id: "berget",
    number: 5,
    title: "Bergsbestigningen",
    subtitle: "Skåne, Kebnekaise eller Everest. Hur högt vågar du?",
    emoji: "⛰️",
    lessonSlug: "05-risk",
    estMinutes: 7,
    status: "coming-soon",
  },
  {
    id: "lagdraften",
    number: 6,
    title: "Lagdraften",
    subtitle: "Drafta 11 bolag. Försvar, mittfält, anfall.",
    emoji: "⚽",
    lessonSlug: "06-diversifiering",
    estMinutes: 7,
    status: "coming-soon",
  },
  {
    id: "lagenheter",
    number: 7,
    title: "Tre lägenheter",
    subtitle: "Sortera pengar mellan ISK, KF och AF.",
    emoji: "🏠",
    lessonSlug: "07-isk-vs-af-vs-kf",
    estMinutes: 5,
    status: "coming-soon",
  },
  {
    id: "bilbesiktning",
    number: 8,
    title: "Bilbesiktningen",
    subtitle: "Lys upp nyckeltalen. Vilka 3 bolag köper du?",
    emoji: "🔦",
    lessonSlug: "08-nyckeltal",
    estMinutes: 7,
    status: "coming-soon",
  },
  {
    id: "panik",
    number: 9,
    title: "Motstå panik-knappen",
    subtitle: "Skärmen blir röd. Knappen pulserar. Klickar du?",
    emoji: "🚨",
    lessonSlug: "09-psykologi",
    estMinutes: 4,
    status: "coming-soon",
  },
  {
    id: "ips",
    number: 10,
    title: "Bygg din IPS",
    subtitle: "Välj 6 regelkort. Se din plan klara 40 år.",
    emoji: "📜",
    lessonSlug: "10-din-egen-plan",
    estMinutes: 12,
    status: "coming-soon",
  },
];

export function moduleById(id: string): ModuleDef | undefined {
  return MODULES.find((m) => m.id === id);
}
